networks:
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.0.0/24"
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: "172.28.0.0/24"

services:
# -----------proxy server -------------
  reverse-proxy:
    container_name: reverse-proxy
    build:
      context: ./reverse-proxy
    networks:
      frontend:
        ipv4_address: 192.168.0.10
      backend:
        ipv4_address: 172.28.0.3
    ports: 
      - "80:80"

# -----------backend server---------------
  server-1:
    container_name: server-1
    build:
      context: ./server/server-1
    networks:
      backend:
        ipv4_address: "172.28.0.5"
    expose:
      - "8000"

  server-2:
    container_name: server-2
    build:
      context: ./server/server-2
    networks:
      backend:
        ipv4_address: "172.28.0.20"

    expose:
      - "8000"

# ----------client----------------
  client:
    container_name: client
    build:
      context: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client/hosts:/etc/hosts:ro
    networks:
      frontend:
        ipv4_address: "192.168.0.2"

    tty: true
    stdin_open: true
